# APARENCIA E CORES
# Define o terminal interno do tmux como tmux-256color
# (evita o modo 'screen' antigo e habilita suporte a 256 cores)
set -g default-terminal "tmux-256color"

# Garante que todos os terminais usem cores verdadeiras (24-bit / true color)
set -ga terminal-overrides ',*:Tc'


# GERAL
set -g mouse on     # habilita mouse

# índices iniciando em 1
set -g base-index 1
setw -g pane-base-index 1

# altera prefixo (padrão é Ctrl + b)
set -g prefix C-a
bind C-a send-prefix


# GERENCIAMENTO DE JANELAS (ABAS)
bind -r S-H previous-window  # janela anterior
bind -r S-L next-window      # próxima janela

bind -r C-S-H swap-window -t -1 \; select-window -t -1
bind -r C-S-L swap-window -t +1 \; select-window -t +1
bind Tab last-window        # move para a última janela ativa (equivala ao Alt + Tab)

bind W command-prompt "rename-window '%%'"  # renomeia a janela (padrão: ^b + ,)
bind X kill-window                          # fecha a janela atual (padrão: ^ + &)


# GERENCIAMENTO DE PAINEIS (DIVISOES)
# splits mais intuitivos
bind-key | split-window -h -c "{pane_current_path}"
bind-key - split-window -v -c "{pane_current_path}"

# troca a posição
bind -r h swap-pane -U
bind -r j swap-pane -D
bind -r k swap-pane -U
bind -r l swap-pane -D

#bind -r H swap-pane -U
#bind -r J swap-pane -D
#bind -r K swap-pane -U
#bind -r L swap-pane -D

# resize com Alt + hjkl (sem prefixo)
bind -n M-h resize-pane -L 2
bind -n M-j resize-pane -D 2
bind -n M-k resize-pane -U 2
bind -n M-l resize-pane -R 2

#bind -n M-H resize-pane -L 2
#bind -n M-J resize-pane -D 2
#bind -n M-K resize-pane -U 2
#bind -n M-L resize-pane -R 2


# MODO COPIA
bind Enter copy-mod     # define enter para entrar no modo copia

setw -g mode-keys vi    # teclas estilo vim no copy-mode

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi Escape send -X cancel


